sudo: true
language: cpp
compiler: gcc
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: sudo apt-get install -qq g++-5

script: 
  - ./build_test.sh
  - ./travis_qmake_gcc_cpp11_boost_test_gcov_test.sh
  - ./build.sh
  - ./get_code_cov.sh
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
